// Converted from .qc on 05/02/2016

#include "g_local.h"
#include "fb_globals.h"

// FIXME: Globals
extern gedict_t* dropper;

void S_time_error() {
	traveltime = 1000000;
}

#define SUBZONE_TIME_FUNCTION(x) \
void S ## x ## _time_() { \
	traveltime = zone_time + middle_marker->fb.subzones[x - 1].time; \
}

void S_path_marker_error() {
	next_marker = NULL;
}

#define SUBZONE_PATH_MARKER_FUNCTION(x) \
void S ## x ##_path_marker() { \
	next_marker = from_marker->fb.subzones[x - 1].next_marker; \
}

void Z_next_zone_marker_error() {
	next_marker = NULL;
}

// TODO: remove
#define NEXT_ZONE_FUNCTION(x) \
void Z ## x ## _next_zone_marker() { \
	next_marker = from_marker->fb.zones[x - 1].next_zone; \
}

void Z_sight_from_marker_error() {
	look_marker = NULL;
}

#define ZONE_SIGHT_FROM_FUNCTION(x) \
void Z ## x ## _sight_from_marker() { \
	look_marker = to_marker->fb.zones[x - 1].sight_from; \
}

void Z_higher_sight_from_marker_error() {
	look_marker = NULL;
}

#define ZONE_HIGHER_SIGHT_FROM_FUNCTION(x) \
void Z ## x ## _higher_sight_from_marker() { \
	look_marker = to_marker->fb.zones[x - 1].higher_sight_from; \
}

void Z_sight_from_time_error() {
	look_traveltime = 1000000;
}

#define ZONE_SIGHT_FROM_TIME_FUNCTION(x) \
void Z ## x ## _sight_from_time() { \
	look_traveltime = to_marker->fb.zones[x - 1].sight_from_time; \
}

void Z_marker_error() {
	middle_marker = dropper;
	zone_time = 1000000;
}

#define ZONE_MARKER_FUNCTION(x) \
void Z ## x ## _marker() { \
	if (path_normal) { \
		middle_marker = from_marker->fb.zones[x - 1].marker; \
		zone_time = from_marker->fb.zones[x - 1].time; \
	} \
	else { \
		middle_marker = from_marker->fb.zones[x - 1].reverse_marker; \
		zone_time = from_marker->fb.zones[x - 1].reverse_time; \
	} \
}

void Z_path_marker_error() {
	next_marker = NULL;
}

#define ZONE_PATH_MARKER_FUNCTION(x) \
void Z ## x ## _path_marker() { \
	if (path_normal) { \
		next_marker = from_marker->fb.zones[x - 1].next; \
	} \
	else  { \
		next_marker = from_marker->fb.zones[x - 1].reverse_next; \
	} \
}

SUBZONE_TIME_FUNCTION(1)
SUBZONE_TIME_FUNCTION(2)
SUBZONE_TIME_FUNCTION(3)
SUBZONE_TIME_FUNCTION(4)
SUBZONE_TIME_FUNCTION(5)
SUBZONE_TIME_FUNCTION(6)
SUBZONE_TIME_FUNCTION(7)
SUBZONE_TIME_FUNCTION(8)
SUBZONE_TIME_FUNCTION(9)
SUBZONE_TIME_FUNCTION(10)
SUBZONE_TIME_FUNCTION(11)
SUBZONE_TIME_FUNCTION(12)
SUBZONE_TIME_FUNCTION(13)
SUBZONE_TIME_FUNCTION(14)
SUBZONE_TIME_FUNCTION(15)
SUBZONE_TIME_FUNCTION(16)
SUBZONE_TIME_FUNCTION(17)
SUBZONE_TIME_FUNCTION(18)
SUBZONE_TIME_FUNCTION(19)
SUBZONE_TIME_FUNCTION(20)
SUBZONE_TIME_FUNCTION(21)
SUBZONE_TIME_FUNCTION(22)
SUBZONE_TIME_FUNCTION(23)
SUBZONE_TIME_FUNCTION(24)
SUBZONE_TIME_FUNCTION(25)
SUBZONE_TIME_FUNCTION(26)
SUBZONE_TIME_FUNCTION(27)
SUBZONE_TIME_FUNCTION(28)
SUBZONE_TIME_FUNCTION(29)
SUBZONE_TIME_FUNCTION(30)
SUBZONE_TIME_FUNCTION(31)
SUBZONE_TIME_FUNCTION(32)

SUBZONE_PATH_MARKER_FUNCTION(1)
SUBZONE_PATH_MARKER_FUNCTION(2)
SUBZONE_PATH_MARKER_FUNCTION(3)
SUBZONE_PATH_MARKER_FUNCTION(4)
SUBZONE_PATH_MARKER_FUNCTION(5)
SUBZONE_PATH_MARKER_FUNCTION(6)
SUBZONE_PATH_MARKER_FUNCTION(7)
SUBZONE_PATH_MARKER_FUNCTION(8)
SUBZONE_PATH_MARKER_FUNCTION(9)
SUBZONE_PATH_MARKER_FUNCTION(10)
SUBZONE_PATH_MARKER_FUNCTION(11)
SUBZONE_PATH_MARKER_FUNCTION(12)
SUBZONE_PATH_MARKER_FUNCTION(13)
SUBZONE_PATH_MARKER_FUNCTION(14)
SUBZONE_PATH_MARKER_FUNCTION(15)
SUBZONE_PATH_MARKER_FUNCTION(16)
SUBZONE_PATH_MARKER_FUNCTION(17)
SUBZONE_PATH_MARKER_FUNCTION(18)
SUBZONE_PATH_MARKER_FUNCTION(19)
SUBZONE_PATH_MARKER_FUNCTION(20)
SUBZONE_PATH_MARKER_FUNCTION(21)
SUBZONE_PATH_MARKER_FUNCTION(22)
SUBZONE_PATH_MARKER_FUNCTION(23)
SUBZONE_PATH_MARKER_FUNCTION(24)
SUBZONE_PATH_MARKER_FUNCTION(25)
SUBZONE_PATH_MARKER_FUNCTION(26)
SUBZONE_PATH_MARKER_FUNCTION(27)
SUBZONE_PATH_MARKER_FUNCTION(28)
SUBZONE_PATH_MARKER_FUNCTION(29)
SUBZONE_PATH_MARKER_FUNCTION(30)
SUBZONE_PATH_MARKER_FUNCTION(31)
SUBZONE_PATH_MARKER_FUNCTION(32)

NEXT_ZONE_FUNCTION(1)
NEXT_ZONE_FUNCTION(2)
NEXT_ZONE_FUNCTION(3)
NEXT_ZONE_FUNCTION(4)
NEXT_ZONE_FUNCTION(5)
NEXT_ZONE_FUNCTION(6)
NEXT_ZONE_FUNCTION(7)
NEXT_ZONE_FUNCTION(8)
NEXT_ZONE_FUNCTION(9)
NEXT_ZONE_FUNCTION(10)
NEXT_ZONE_FUNCTION(11)
NEXT_ZONE_FUNCTION(12)
NEXT_ZONE_FUNCTION(13)
NEXT_ZONE_FUNCTION(14)
NEXT_ZONE_FUNCTION(15)
NEXT_ZONE_FUNCTION(16)
NEXT_ZONE_FUNCTION(17)
NEXT_ZONE_FUNCTION(18)
NEXT_ZONE_FUNCTION(19)
NEXT_ZONE_FUNCTION(20)
NEXT_ZONE_FUNCTION(21)
NEXT_ZONE_FUNCTION(22)
NEXT_ZONE_FUNCTION(23)
NEXT_ZONE_FUNCTION(24)

ZONE_SIGHT_FROM_FUNCTION(1)
ZONE_SIGHT_FROM_FUNCTION(2)
ZONE_SIGHT_FROM_FUNCTION(3)
ZONE_SIGHT_FROM_FUNCTION(4)
ZONE_SIGHT_FROM_FUNCTION(5)
ZONE_SIGHT_FROM_FUNCTION(6)
ZONE_SIGHT_FROM_FUNCTION(7)
ZONE_SIGHT_FROM_FUNCTION(8)
ZONE_SIGHT_FROM_FUNCTION(9)
ZONE_SIGHT_FROM_FUNCTION(10)
ZONE_SIGHT_FROM_FUNCTION(11)
ZONE_SIGHT_FROM_FUNCTION(12)
ZONE_SIGHT_FROM_FUNCTION(13)
ZONE_SIGHT_FROM_FUNCTION(14)
ZONE_SIGHT_FROM_FUNCTION(15)
ZONE_SIGHT_FROM_FUNCTION(16)
ZONE_SIGHT_FROM_FUNCTION(17)
ZONE_SIGHT_FROM_FUNCTION(18)
ZONE_SIGHT_FROM_FUNCTION(19)
ZONE_SIGHT_FROM_FUNCTION(20)
ZONE_SIGHT_FROM_FUNCTION(21)
ZONE_SIGHT_FROM_FUNCTION(22)
ZONE_SIGHT_FROM_FUNCTION(23)
ZONE_SIGHT_FROM_FUNCTION(24)

ZONE_HIGHER_SIGHT_FROM_FUNCTION(1)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(2)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(3)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(4)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(5)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(6)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(7)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(8)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(9)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(10)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(11)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(12)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(13)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(14)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(15)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(16)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(17)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(18)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(19)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(20)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(21)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(22)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(23)
ZONE_HIGHER_SIGHT_FROM_FUNCTION(24)

ZONE_SIGHT_FROM_TIME_FUNCTION(1)
ZONE_SIGHT_FROM_TIME_FUNCTION(2)
ZONE_SIGHT_FROM_TIME_FUNCTION(3)
ZONE_SIGHT_FROM_TIME_FUNCTION(4)
ZONE_SIGHT_FROM_TIME_FUNCTION(5)
ZONE_SIGHT_FROM_TIME_FUNCTION(6)
ZONE_SIGHT_FROM_TIME_FUNCTION(7)
ZONE_SIGHT_FROM_TIME_FUNCTION(8)
ZONE_SIGHT_FROM_TIME_FUNCTION(9)
ZONE_SIGHT_FROM_TIME_FUNCTION(10)
ZONE_SIGHT_FROM_TIME_FUNCTION(11)
ZONE_SIGHT_FROM_TIME_FUNCTION(12)
ZONE_SIGHT_FROM_TIME_FUNCTION(13)
ZONE_SIGHT_FROM_TIME_FUNCTION(14)
ZONE_SIGHT_FROM_TIME_FUNCTION(15)
ZONE_SIGHT_FROM_TIME_FUNCTION(16)
ZONE_SIGHT_FROM_TIME_FUNCTION(17)
ZONE_SIGHT_FROM_TIME_FUNCTION(18)
ZONE_SIGHT_FROM_TIME_FUNCTION(19)
ZONE_SIGHT_FROM_TIME_FUNCTION(20)
ZONE_SIGHT_FROM_TIME_FUNCTION(21)
ZONE_SIGHT_FROM_TIME_FUNCTION(22)
ZONE_SIGHT_FROM_TIME_FUNCTION(23)
ZONE_SIGHT_FROM_TIME_FUNCTION(24)

ZONE_MARKER_FUNCTION(1)
ZONE_MARKER_FUNCTION(2)
ZONE_MARKER_FUNCTION(3)
ZONE_MARKER_FUNCTION(4)
ZONE_MARKER_FUNCTION(5)
ZONE_MARKER_FUNCTION(6)
ZONE_MARKER_FUNCTION(7)
ZONE_MARKER_FUNCTION(8)
ZONE_MARKER_FUNCTION(9)
ZONE_MARKER_FUNCTION(10)
ZONE_MARKER_FUNCTION(11)
ZONE_MARKER_FUNCTION(12)
ZONE_MARKER_FUNCTION(13)
ZONE_MARKER_FUNCTION(14)
ZONE_MARKER_FUNCTION(15)
ZONE_MARKER_FUNCTION(16)
ZONE_MARKER_FUNCTION(17)
ZONE_MARKER_FUNCTION(18)
ZONE_MARKER_FUNCTION(19)
ZONE_MARKER_FUNCTION(20)
ZONE_MARKER_FUNCTION(21)
ZONE_MARKER_FUNCTION(22)
ZONE_MARKER_FUNCTION(23)
ZONE_MARKER_FUNCTION(24)

ZONE_PATH_MARKER_FUNCTION(1)
ZONE_PATH_MARKER_FUNCTION(2)
ZONE_PATH_MARKER_FUNCTION(3)
ZONE_PATH_MARKER_FUNCTION(4)
ZONE_PATH_MARKER_FUNCTION(5)
ZONE_PATH_MARKER_FUNCTION(6)
ZONE_PATH_MARKER_FUNCTION(7)
ZONE_PATH_MARKER_FUNCTION(8)
ZONE_PATH_MARKER_FUNCTION(9)
ZONE_PATH_MARKER_FUNCTION(10)
ZONE_PATH_MARKER_FUNCTION(11)
ZONE_PATH_MARKER_FUNCTION(12)
ZONE_PATH_MARKER_FUNCTION(13)
ZONE_PATH_MARKER_FUNCTION(14)
ZONE_PATH_MARKER_FUNCTION(15)
ZONE_PATH_MARKER_FUNCTION(16)
ZONE_PATH_MARKER_FUNCTION(17)
ZONE_PATH_MARKER_FUNCTION(18)
ZONE_PATH_MARKER_FUNCTION(19)
ZONE_PATH_MARKER_FUNCTION(20)
ZONE_PATH_MARKER_FUNCTION(21)
ZONE_PATH_MARKER_FUNCTION(22)
ZONE_PATH_MARKER_FUNCTION(23)
ZONE_PATH_MARKER_FUNCTION(24)

// 
void SightMarker(gedict_t* from_marker) {
	gedict_t* marker_;
	extern vec3_t to_marker_pos;

	assert (from_marker);

	look_traveltime = 1000000;
	middle_marker = from_marker;
	zone_time = 0;
	VectorAdd(to_marker->s.v.absmin, to_marker->s.v.view_ofs, to_marker_pos);
	to_marker_pos[2] += 32;
	
	marker_ = from_marker->fb.Z_head;
	while (marker_) {
		traceline(to_marker_pos[0], to_marker_pos[1], to_marker_pos[2], marker_->s.v.absmin[0] + marker_->s.v.view_ofs[0], marker_->s.v.absmin[1] + marker_->s.v.view_ofs[1], marker_->s.v.absmin[2] + marker_->s.v.view_ofs[2] + 32, true, world);
		if (g_globalvars.trace_fraction == 1) {
			marker_->fb.sub_arrival_time();
			if (look_traveltime > traveltime) {
				if (strneq(marker_->s.v.classname, "trigger_teleport")) {
					look_traveltime = traveltime;
					look_marker = marker_;
					marker_->fb.near_teleport = NULL;
				}
				else if (streq(marker_->s.v.classname, "trigger_teleport")) {
					marker_->fb.near_teleport = marker_;
				}
			}
		}
		marker_ = marker_->fb.Z_next;
	}
}

void HigherSightMarker(gedict_t* from_marker) {
	gedict_t* marker_;
	vec3_t marker_pos;
	vec3_t to_marker_pos;

	look_traveltime = 1000000;
	middle_marker = from_marker;
	zone_time = 0;
	VectorAdd(to_marker->s.v.absmin, to_marker->s.v.view_ofs, to_marker_pos);
	to_marker_pos[2] += 32;

	marker_ = from_marker->fb.Z_head;
	while (marker_) {
		VectorAdd(marker_->s.v.absmin, marker_->s.v.view_ofs, marker_pos);
		marker_pos[2] += 32;

		if (marker_pos[2] - to_marker_pos[2] >= 40) {
			if (VectorDistance(marker_pos, to_marker_pos) <= 1000) {
				traceline(to_marker_pos[0], to_marker_pos[1], to_marker_pos[2], marker_pos[0], marker_pos[1], marker_pos[2], true, world);
				if (g_globalvars.trace_fraction == 1) {
					marker_->fb.sub_arrival_time();
					if (look_traveltime > traveltime) {
						if (strneq(marker_->s.v.classname, "trigger_teleport")) {
							look_traveltime = traveltime;
							look_marker = marker_;
							marker_->fb.near_teleport = NULL;
						}
						else if (streq(marker_->s.v.classname, "trigger_teleport")) {
							marker_->fb.near_teleport = marker_;
						}
					}
				}
			}
		}
		marker_ = marker_->fb.Z_next;
	}
}

